### ISSUE TITLE
Compile components on application boot

### ISSUE THREAD

**Issue by joelhawksley** [github/actionview-component#100]
In production, it would probably make sense to `compile` all descendents of `ActionView::Component::Base`, so that components render quickly on the first request, instead of compiling lazily as they do now.

**Comment by kaspermeyer** [comment]
I'd be interested in giving this a go, @joelhawksley!

**Comment by joelhawksley** [comment]
Thanks @kaspermeyer! I've assigned it to you. Feel free to unassign yourself if you decide not to take it on.
