### ISSUE TITLE
Allow rendering collection of components

### ISSUE THREAD

**Issue by vinistock** [github/actionview-component#114]
When rendering jbuilder partials, the following can be used instead of explicitly writing a loop that renders each partial:

```ruby
json.partial! "posts/post", collection: @posts, as: :post
```

It would be interesting if we could have something similar for components. The example below assumes a PostComponent is defined.

```ruby
# posts_controller.rb

class PostsController < ApplicationController
  def index
    @posts = Post.scope_that_queries_the_right_posts(params)
  end
end

# app/views/posts/index.html.erb

<%= render @posts %>
```

In this case, for each record we would get the associated component and render it. I'd love some feedback and implementations ideas. I can work on some implementation suggestions.

**Comment by juanmanuelramallo** [comment]
It seems like this is related to #21 no?

**Comment by joelhawksley** [comment]
@juanmanuelramallo @vinistock let's close this in favor of https://github.com/github/actionview-component/issues/21 ❤️
