### ISSUE TITLE
V2 Roadmap - Contributions welcome!

### ISSUE THREAD

**Issue by joelhawksley** [github/actionview-component#132]
👋 hello folks!

As we look towards upstreaming our work on `actionview-component` into Rails, it feels like it might be time to think about working towards a major release.

I've added the `v2` label to issues we think would make sense to get in ahead of this release: https://github.com/github/actionview-component/issues?q=is%3Aissue+is%3Aopen+label%3Av2

I'd love to hear what you think we should be sure to include in V2 ❤️

**Comment by xdmx** [comment]
Hey @joelhawksley, do you already have a date in mind as a deadline for submitting it for upstreaming?

I'm sure that having people from the core already working/touching/reviewing/using this code may speed up the process, but I was just wondering if you've thought about a date you'd like to do it, as after some date there will be a feature freeze for getting ready for the final 6.1 (May 2020 / Railsconf could be a target date for having a 6.1 beta / rc / final :man_shrugging:)

**Comment by joelhawksley** [comment]
@xdmx in general, we'd hope that this makes it into 6.1.

More specifically, I think we need to hit `v2` before we give upstreaming too much thought. I'm hoping we can get there in the next month or two.
