### ISSUE TITLE
Should variants fall back to default template?

### ISSUE THREAD

**Issue by asgerb** [github/actionview-component#141]
Thanks a lot for the amazing work! I'm really happy to be using this gem, it's bringing some much needed clarity and testability to my views 🙂

I'm finding the newly implemented variants logic a bit surprising though. Notably the `:variant_exists` validation, which forces me to add templates for every variant. 

`ActionPack::Variants` simply falls back to the default template, in case there is no template defined for the variant and I find this to be a nicer way to go about it as it's a more flexible approach, allowing you to define variant templates only for the components that need it.

What are your thoughts? I'm very open to submitting a PR, but wanted to hear you out first 🙂

**Comment by joelhawksley** [comment]
@asgerb if that's how things work in Rails, a PR would be more than welcome!

**Comment by joelhawksley** [comment]
Closed by https://github.com/github/actionview-component/pull/147 ❤️
