### ISSUE TITLE
Allow components to have multiple content areas

### ISSUE THREAD

**Issue by kylefox** [github/actionview-component#144]
First of, this library looks _awesome_ and I can't wait to start using it :)

Something that would be really nice is the ability for a component to have more than one output area, or _"outlet"_ (for lack of a better term). Essentially, the idea is very similar to using `yield(:foo)` and `content_for(:foo)` in normal Rails views.

Often, the dynamic content within a component cannot be declared within a single block. One example is a modal window that has a title, body, and row of buttons:

![image](https://user-images.githubusercontent.com/37838/70283669-45f21580-177f-11ea-94be-c8138c9daf62.png)

This would be a really cool way to render this modal with a title (static string), body (block), and footer (block). The block could now be passed an instance of the component (or perhaps something like component builder) which could act to capture explicitly named blocks:

```erb
<%= render(ModalComponent, title: 'Are you sure?') do |modal| %>
  <%= modal.body do %>
    <p>This is some content that would go in the modal body.</p>
  <% end %>

  <%= modal.footer do %>
    <%= link_to 'Cancel', '#', class: 'btn btn-secondary', data: { dismiss: :modal } %>
    <%= button_to 'Confirm', confirmation_path, class: 'btn btn-primary' %>
  <% end %>
<% end %>
```

The component template might look something like this:

```erb
<!-- app/components/modal_component.html.erb -->
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title"><%= title %></h4>
    </div>

    <div class="modal-body">
      <%= body %>
    </div>

    <div class="modal-footer">
      <%= footer %>
    </div>
  </div>
</div>
```

I think this would make components far more flexible, and allow us to write less repetitive markup when using the components. Without something like this, the developer must remember to include `<div class="modal-body">` and `<div class="modal-footer">` whenever the component is used:

```erb
<%= render(ModalComponent, title: 'Are you sure?') do %>
  <div class="modal-body">
    <p>This is some content that would go in the modal body.</p>
  </div>

  <div class="modal-footer">
    <%= link_to 'Cancel', '#', class: 'btn btn-secondary', data: { dismiss: :modal } %>
    <%= button_to 'Confirm', confirmation_path, class: 'btn btn-primary' %>
  </div>
<% end %>
```

The need to wrap content in these classes feels like an implementation detail that should be the responsibility of the component itself.

Now, this one occurrence might not seem so bad. But imagine this pattern repeated many, many places in the application. Developers must remember to mark up the content within the block in a specific way (thereby "leaking" some of the internals of the component), which can result in mistakes and make the code more difficult to maintain.

If there's support for something like this, I think the next step would be to discuss the API and syntax for outlets. I'd be happy to hack on this if there's interest!

**Comment by joelhawksley** [comment]
@kylefox this is _fantastic_. I love the proposed API.

I'd love to see even a draft PR that takes a crack at this. I'm also happy to chat this through / hack on it together: joelhawksley@github.com

**Comment by kylefox** [comment]
@joelhawksley Cool :)

Do you think it's worth distinguishing attributes (like `title:`) and outlets (like `modal.body`) as distinct concepts?

After posting my initial comment I began wondering if the two mechanisms for providing content to the component could be used interchangeably:

```erb
<!-- Provide `body` content with a block -->
<%= render(ModalComponent, title: 'Are you sure?') do |modal| %>
  <%= modal.body do %>
    <p>This is some content that would go in the modal body.</p>
  <% end %>

  <%= modal.footer do %>
    <%= link_to 'Cancel', '#', class: 'btn btn-secondary', data: { dismiss: :modal } %>
    <%= button_to 'Confirm', confirmation_path, class: 'btn btn-primary' %>
  <% end %>
<% end %>

<!-- Provide `body` content with a parameter -->
<%= render(ModalComponent, title: 'Are you sure?', body: 'This is some content that would go in the modal body.') do |modal| %>
  <%= modal.footer do %>
    <%= link_to 'Cancel', '#', class: 'btn btn-secondary', data: { dismiss: :modal } %>
    <%= button_to 'Confirm', confirmation_path, class: 'btn btn-primary' %>
  <% end %>
<% end %>
```

As I begin mapping our existing application to components, in some instances the content is a simple string, and in other cases it's more complex HTML. An example might be help text that appears below a form input — in many cases a simple string is all that's required (which parameters work well for) but _occasionally_ we need to insert a couple paragraphs, or a link, etc. (which blocks work well for). The ability to use either interchangeably would give us the flexibility to use the same component in both scenarios.

(We could of course use the block syntax everywhere for the help text, but the syntax is a lot more clunky — if the content is a simple string most of the time, parameters would be preferred).

On the other hand, maybe conflating attributes and outlets increases cognitive overhead for developers, and technical complexity internally?

You have far more experience using components than me, so I'd love to hear your take on this.

**Comment by joelhawksley** [comment]
I love the interchangeability, since you're right that sometimes you might just want to pass a string while other times you might want to pass a whole block. 

Also, given that we are going to support rendering components in controllers, where having a block argument with ERB in it is unlikely to work, having the option to set content via a `content` param would be really convenient!

**Comment by mellowfish** [comment]
This is great. What do you think the component code would look like? Just the normal 
```ruby
attr_accessor :title, :body, :footer
```
or something else?

**Comment by kylefox** [comment]
@mellowfish Yeah, exactly — I was thinking that it'd be much simpler for developers if the API for specifying attributes and blocks was the same. And it especially makes sense if attributes/blocks can be used interchangeably.

However, validation might complicate things significantly 😕

Consider the [example](https://github.com/github/actionview-component#implementation) from the README:

```ruby
class TestComponent < ActionView::Component::Base
  validates :content, :title, presence: true

  def initialize(title:)
    @title = title
  end

  private

  attr_reader :title
end
```

Also from the README:

> Components are validated after initialization, but before rendering.

So from what I understand, the component would fail validation if used this in way:

```erb
<%= render(TestComponent) do |component| %>
  <%= component.title do %>
    <p>Hello, World!</p>
  <% end %>
<% end %>
```

I'll have to dig into the guts more to understand how validation is happening, and what the consequences might be if validation was performed _after_ rendering. I don't think block content can be validated until the component is fully rendered.

It would be really nice if we could validate block content, but that might necessitate deeper changes than we're willing to make right now. Perhaps V1 of this API doesn't support validations, and the workaround is for developers to _not_ validate attributes that are intended to be used as blocks?

**Comment by bostanio** [comment]
Would an API like `content_for` be a more natural fit and parallel to existing Rails patterns? 

```ruby
<!-- Provide `body` content with a block -->
<%= render(ModalComponent, title: 'Are you sure?') do |modal| %>
  <%= modal.content_for :body do %>
    <p>This is some content that would go in the modal body.</p>
  <% end %>

  <%= modal.content_for :footer do %>
    <%= link_to 'Cancel', '#', class: 'btn btn-secondary', data: { dismiss: :modal } %>
    <%= button_to 'Confirm', confirmation_path, class: 'btn btn-primary' %>
  <% end %>
<% end %>
```

**Comment by joelhawksley** [comment]
@bostanio oh, I like that! I think that using the `content_for` API makes sense, assuming we can make it behave in a manner consistent with how it currently behaves.

**Comment by kylefox** [comment]
@bostanio Good idea — I prefer that syntax, and it will probably be more straightforward to implement.

**Comment by bostanio** [comment]
@kylefox Yup I would expect the implementation to be much simpler too. I'd imagine that we could have a `yield :body` kind of syntax in the components view too. I'd also imagine that we could still validate the "outlet" names against known attributes of the component etc.

**Comment by bostanio** [comment]
I'm hacking on a version of this and have something just about working. The nice surprise is that validation happens after capture of the block passed to the component so we *can* validate properties set via content_for!

**Comment by bostanio** [comment]
The interesting discovery (thanks to an existing test example) is using the method name `content_for` as I suggested has the effect of changing the method in the Component's view file as well. This commit 4a52b3db585662a020266cb5a97ba2adaba445f9 explicitly added support for using the existing `content_for` in components views. I doubt we want to mess with that.

I see a couple of choices a) we pick a different name b) we construct some mechanism for only applying our magic if the attribute you pass matches a named attribute of the component otherwise it passes through to the old behavior. a) is simple, a bit less elegant but unlikely to be confusing. 

Thoughts on an alternative name?

**Comment by kylefox** [comment]
I think this can be closed now that [content areas](https://github.com/github/actionview-component#content-areas) from #161 are available
