### ISSUE TITLE
render_inline produces bad output for some templates

### ISSUE THREAD

**Issue by dark-panda** [github/actionview-component#145]
The following line in the test helpers produces incorrect results depending on the template being rendered:

https://github.com/github/actionview-component/blob/99fc8dd285cf98f3121fff45f590d6be5da550bc/lib/action_view/component/test_helpers.rb#L7

This isn't a consistent thing though -- it chokes on certain types of input. Consider the following:

```ruby
Nokogiri::HTML('<script>alert("OK")</script>').css('body > *')
```

This returns an empty string. This will similarly produce empty strings depending on the input -- using `noframes`, `frame`, various other elements will all produce weird input. Here's some other fun results:

```ruby
Nokogiri::HTML("<script>alert</script><b>ok</b>").css("body > *").to_s
# => "<b>ok</b>"
Nokogiri::HTML("<script>alert</script>").css("body > *").to_s
# => ""
Nokogiri::HTML("hello world").css("body > *").to_s
# => "<p>hello world</p>"
```

I'd recommend doing the following instead perhaps:

```ruby
Nokogiri::HTML.fragment(controller.view_context.render(component, args, &block))
```

Which produces the expected result of all of the above examples:

```ruby
Nokogiri::HTML.fragment("<script>alert</script><b>ok</b>").to_s
# => "<script>alert</script><b>ok</b>"
Nokogiri::HTML.fragment("<script>alert</script>").to_s
# => "<script>alert</script>"
Nokogiri::HTML.fragment("hello world").to_s
# => "hello world"
```

**Comment by joelhawksley** [comment]
@dark-panda good catch!

@elia it looks like this change was introduced in https://github.com/github/actionview-component/commit/a7688a4b4826c9914b039ab92dcce33a3ef82d0d#diff-672e600924ab3139bed663637694cdcb. What do you think we should do here?

**Comment by elia** [comment]
@dark-panda @joelhawksley thanks for fixing this!
