### ISSUE TITLE
[1.6.0 - 1.6.1] uninitialized constant ActionView::Component::Base

### ISSUE THREAD

**Issue by afuno** [github/actionview-component#163]
Rails 6.0.2.1

---

**Gemfile:**

```ruby
gem 'actionview-component'
```

**application.rb:**

```ruby
require 'action_view/component/railtie'
```

**body_component.rb:**

```ruby
class BodyComponent < ActionView::Component::Base
  validates :content, presence: true

  def initialize(data: {})
    @data = data
  end

  private

  attr_reader :data
end
```

**layouts.html.slim:**

```slim
= render(BodyComponent, data: { locale: locale })
```

As a result, I get the error:

> NameError - uninitialized constant ActionView::Component::Base

Gem installed on a new application, following the instructions in the [README](https://github.com/github/actionview-component#installation) file.

**Comment by afuno** [comment]
If replace this line:

```ruby
require 'action_view/component/railtie'
```

On this:

```ruby
require 'action_view/component'
```

That everything works.

**Comment by afuno** [comment]
https://github.com/github/actionview-component/pull/162

**Comment by rainerborene** [comment]
You're looking at the `master` branch. Latest version of `actionview-component` wasn't released yet on RubyGems.

**Comment by afuno** [comment]
@rainerborene Oh, okay.

**Comment by joelhawksley** [comment]
My apologies for the confusion here folks. I've published `v1.6.1` which should work with the `rail tie` syntax. Please re-open this if needed ❤️ 🎄

**Comment by afuno** [comment]
@joelhawksley I updated gem to version 1.6.1. Next, I replaced the code with this:

```ruy
require 'action_view/component/railtie'
```

https://github.com/github/actionview-component/compare/v1.6.0..v1.6.1

The application does not start:

```
/Users/afuno/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:79:in `block in load_missing_constant': uninitialized constant ActionView::Component::Base (NameError)
```

Everything works successfully with this code:

``ruby
require 'action_view/component'
```

**Comment by joelhawksley** [comment]
@rainerborene I'm seeing this well in my environment. Might you be able to have a look?

**Comment by rainerborene** [comment]
@joelhawksley done. https://github.com/github/actionview-component/pull/167

**Comment by rainerborene** [comment]
I guess the solution is to specify the `require` path on Gemfile.

```ruby
gem 'actionview-component', require: "action_view/component"
```

**Comment by afuno** [comment]
So what about the current situation? How to install versions 1.60 and 1.61 now? Like this?

```ruby
# config/application.rb
require 'action_view/component'
```

**Comment by afuno** [comment]
At first glance in version 1.6.2 everything is fine.

**Comment by joelhawksley** [comment]
Thanks for resolving this @bostanio ❤️
