### ISSUE TITLE
Preview 'index' page also shows instance variables

### ISSUE THREAD

**Issue by bazzel** [github/actionview-component#169]
I have a preview component that contains some instance variables:
```
class TestComponentPreview < ActionView::Component::Preview
  attr_accessor :some_accessor

  def with_default_title
    render(TestComponent, title: "Test component default")
  end
  ...
end
```

When I navigate to `http://localhost:300/rails/components` both the 'getter' and 'setter' are listed. I know this is easy to fix by changing `ActionView::Component::Preview#examples` but currently I'm having trouble finding the time to set up a unit test for this.

```
# lib/action_view/component/preview.rb
def examples
  public_instance_methods(false)
    .map(&:to_s)
    .reject { |e| (e =~ /=$/) || instance_methods(false).map(&:to_s).include?("#{e}=") }
    .sort
end
```

**Comment by joelhawksley** [comment]
@juanmanuelramallo care to have a look here?

**Comment by juanmanuelramallo** [comment]
Sure thing!

**Comment by juanmanuelramallo** [comment]
@bazzel Sorry for the late answer. 

Do you think a private `attr_accessor` would also work? 

```ruby
class TestComponentPreview < ActionView::Component::Preview
  def with_default_title
    render(TestComponent, title: "Test component default")
  end
  
  ...

  private
  
  attr_accessor :some_accessor
end
```

I don't see why we would need to use attribute accessors publicly on a `ActionView::Component::Preview` object, maybe you can elaborate a bit more the example? I might be missing something.

**Comment by bazzel** [comment]
Haven't thought of using a private variable 😳but that removes the need for filtering out the instance variables. Thanks for the reply!
