### ISSUE TITLE
Ability to pick template rendered by component.

### ISSUE THREAD

**Issue by guilherme-andrade** [github/actionview-component#179]
Hey! I started using your API recently and love it. I wanted to ask however if the following would be in your timeline.

### Feature request
Have the ability to pick the template rendered by the component (similar to Smart / Dumb component architecture in React)

Example: 
```
class Component < ActionView::Component::Base
  validates :attribute, presence: true


  def initialize(attr: {})
    @steps = attr

    template :component_name # this would render the `component_name.html.erb` file
  end
end
```
*Note: `template :template_name` is simply a syntax suggestion*

### Motivation
Reusable component templates, and ability to have Higher level Components inheriting from lower level components. 

#### My scenario:
I have a timeline component I use in various forms. 
It is similar in style in all forms, but its steps vary from form to form, currently forcing me to define the steps in helpers. I would like it to be possible to do the following:

components/timeline_component.rb
```
class TimelineComponent < ActionView::Component::Base
  # ...
  def initialize(steps: [])
    @steps = steps
  end
end
```

components/timelines/form_one.rb
```
class Timelines::FormOneComponent < TimelineComponent
  def initialize
    @steps = [
       # list of steps
    ]

    template :timeline
  end
end
```

and use `render Timelines::FormOneComponent` to render that specific timeline.

**Comment by jonspalmer** [comment]
Would you use case be solved by thinking about the problem as composition rather than inheritance?

components/timeline_component.rb
```ruby
class TimelineComponent < ActionView::Component::Base
  # ...
  def initialize(steps: [])
    @steps = steps
  end
end
```

components/timelines/form_one_component.rb
```ruby
class Timelines::FormOneComponent < ActionView::Component::Base
  attr_reader :steps

  def initialize
    @steps = [
       # list of steps
    ]
  end
end
```

components/timelines/form_one_component.html.erb
```erb
<%= render(TimelineComponent, steps: steps) =>
```

It's one more view file than the requested feature but more flexible.

**Comment by guilherme-andrade** [comment]
@jonspalmer yeah you're right. I will go with this 👍

**Comment by joelhawksley** [comment]
I agree with @jonspalmer here. Closing ❤️
