### ISSUE TITLE
Template changes not reflected in development

### ISSUE THREAD

**Issue by joelhawksley** [github/actionview-component#19]
In https://github.com/github/actionview-component/issues/15, @metade and @mikker both reported that, when in development mode, edits to a component's template were not reflected when reloading a page rendering the component.

Ideally, edits should be reflected when the page is reloaded.

**Comment by pmackay** [comment]
I have also found this to be an issue that would be great to resolve. I did a small monkey patch to workaround it, so a fix would be awesome :)

**Comment by joelhawksley** [comment]
Closed by #20.
