### ISSUE TITLE
Upgrade from 1.12 -> 1.14 (and 1.14.1) causes errors `to_partial_path` must be implemented?

### ISSUE THREAD

**Issue by bunnymatic** [github/actionview-component#243]
After an upgrade from 1.12 to 1.14, my app completely fell over because none of the components will render any more.  They complain that `to_partial_path` is not available.

I made a simpler repro case which was to use the generator to build a brand new component, uncomment the tests and run them.  And that fails for the same reason. Hopefully the steps below are enough to expose the problem.

## Steps to reproduce 
* upgrade to 1.14 gem version
* create a new component ```bundle exec rails g component My name``` (answer no to content)
* edit the spec uncommenting out templated spec
```spec/components/my_component_spec.rb
require "rails_helper"

RSpec.describe MyComponent, type: :component do
  it "renders something useful" do
    expect(
      render_inline(described_class, attr: "value") { "Hello, components!" }.css("p").to_html
    ).to include(
      "Hello, components!"
    )
  end
end
```
* run the tests
* they fail because `to_partial_path` has not been implemented.

### Expected behavior
* a brand new component should at a minimum be able to render itself and test should fail because the template content doesn't match... not because it can't render

### Actual behavior
```
% bundle exec rspec spec/components/my_component_spec.rb
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 37481

MyComponent
  renders something useful (FAILED - 1)

Failures:

  1) MyComponent renders something useful
     Failure/Error: render_inline(described_class, attr: "value") { "Hello, components!" }.css("p").to_html

     ArgumentError:
       'MyComponent' is not an ActiveModel-compatible object. It must implement :to_partial_path.
     # ./spec/components/my_component_spec.rb:6:in `block (2 levels) in <top (required)>'

Finished in 0.00827 seconds (files took 1.42 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/components/my_component_spec.rb:4 # MyComponent renders something useful
```

### System configuration
**Rails version**:
6.0.2
**Ruby version**:
2.6.5
**Gem version**:
3.0.3

**Comment by joelhawksley** [comment]
@bunnymatic good catch! It looks like I forgot to update the generator 🤦‍♂. I'll look at this now.

You mention that your other components are failing to render. Can you provide an example component and the render call site that is failing?

**Comment by bunnymatic** [comment]
That does not appear to solve the problem.  

In the same repo, upgrading to 1.14.1, my app won't render components in tests or IRL.

To demonstrate, I added a new component, added a `plain.html.slim` page which only renders that component (with no layout for simplicity) and I get the same error.


```ruby
# components/application_view_component.rb
class ApplicationViewComponent < ViewComponent::Base; end
```
```ruby
# components/my_component.rb
class MyComponent < ApplicationViewComponent
  def initialize(name:)
    @name = name
  end
end
```
```slim
# components/my_component.html.slim
div = name
```

Added a route to a page with no layout that just renders 1 component
``` views/pages/plain.html.slim
= render MyComponent.new(name: 'jon')
```

I get ```'#<MyComponent:0x00007fc2f83015e8 @name="jon">' is not an ActiveModel-compatible object. It must implement :to_partial_path.```

<img width="810" alt="Screen Shot 2020-03-04 at 10 39 47 AM" src="https://user-images.githubusercontent.com/427380/75911555-958ac080-5e04-11ea-85f6-8a70cd3a89a0.png">

**Comment by bunnymatic** [comment]
I also tried regenerating a component with the new generator but same issue.  Still won't render in a test or in the app with `missing to_partial_path`.

**Comment by joelhawksley** [comment]
@bunnymatic how are you loading the gem in your application? Are you including it in your `application.rb`?

This error means that the monkey patch on `render` isn't working properly.

**Comment by bunnymatic** [comment]
That was it...

```
diff --git a/config/application.rb b/config/application.rb
index 3447a297..fc5e0fef 100644
--- a/config/application.rb
+++ b/config/application.rb
@@ -1,6 +1,7 @@
 require_relative "boot"
 require "rails/all"
-require "action_view/component"
+require "view_component/engine"
+
```

I missed the first line in the migration readme *and* `action_view/component` still exists so that require did not fail so I didn't catch it.

Thanks

**Comment by joelhawksley** [comment]
Thanks for following up, and sorry for the trouble!

**Comment by holman** [comment]
Just as an aside for The Future Googlers- we ran into this problem because we had `render(NeatoComponent)` calls still. A bit confusing given the error stemming from it. Changing them to `render(NeatoComponent.new)` calls fixed things up. 🌈
