### ISSUE TITLE
Lower ruby requirement to match Rails 5

### ISSUE THREAD

**Issue by andrewmarkle** [github/actionview-component#32]
Hey! Love what you're doing here! 

We're testing this out in our app (running Rails 5) and I'm wondering if you would consider lowering the ruby requirement? Right now it's set to 2.5 + (which is great for Rails 6 but leaves out us Rails 5 folks who aren't as up-to-date). 

I've been running this with Ruby 2.4 and works fine. Rails 5 has the requirement of ruby 2.2 or higher. 

Happy to open a PR if you think it's a good idea!

**Comment by joelhawksley** [comment]
@andrewmarkle https://github.com/github/actionview-component/pull/35 adds support for Ruby 2.3 and Rails 5. 

I was not able to test against Ruby 2.2 in CI, so I picked 2.3 out of an abundance of caution.

**Comment by joelhawksley** [comment]
@andrewmarkle mind testing `v1.2.1` with your app? It supports Ruby 2.3/Rails 5.
