### ISSUE TITLE
Allow rendering components in the controller

### ISSUE THREAD

**Issue by ushis** [github/actionview-component#38]
Hi @joelhawksley 

I am happy to see a view model lib, that integrates smoothly with rails. While playing around with `ActionView::Component` i noticed that it is not possible to render components in the controller. I saw, that you are monkey patching `ActionView::Base#render`. So i tried to override the `render` method in my `ApplicationController` in a similar way, but without success.

At the moment users are forced to write templates with a single line: `<%= render(PostShowComponent, post: @post) %>`. It would be great to have an API like this:

```ruby 
class PostsController < ApplicationController
  def show 
    post = Post.find(params[:id])
    render(PostShowComponent, post: post)
  end
end
```
I could provide a PR with a failing feature test, if that helps. 

Thank you , ushi

P.S. Found a workaround. Maybe its a good starting point:

```ruby
class ApplicationController
  private

  def render_component(component, args, **options)
    options = options.reverse_merge(layout: true)
    render(html: view_context.render(component, args), options)
  end 
end
```

**Comment by joelhawksley** [comment]
@ushis I agree. This is definitely something that should work. 

I have no objections to the proposed API.

One thing I'm curious about: Do you think we should support passing content to components via a block argument when rendering them from a controller?

**Comment by ushis** [comment]
@joelhawksley Thanks for the feedback. 

> One thing I'm curious about: Do you think we should support passing content to components via a block argument when rendering them from a controller?

Depends on the complexity. It would enable the implementation of layouts using components:

```ruby
render(AdminLayoutComponent, current_user: user) do 
  render(PostShowComponent, post: post)
end
```

This approach leads to other questions, because `ActionView` depends on a controller in some cases. E.g. to render `csrf_meta_tags` in the layout, we need a controller, that provides `request_forgery_protection_token`. But i think this is addressed in #28 

What i want to say: It would be nice, but not necessary in the first iteration, if too complex.

How do you want to proceed? Opening a PR that monkeypatches ActionController::Base?

**Comment by joelhawksley** [comment]
@ushis a monkey patch is probably a good place to start! I'd definitely welcome a PR.

**Comment by joelhawksley** [comment]
@kaspermeyer I know you had some interest in this one a while ago. Might you be able to have a crack at it?

**Comment by kaspermeyer** [comment]
Absolutely! Thanks for pinging me on this, @joelhawksley ❤️ I can dedicate some time at the end of this week to get started on this along with tests for pre-compiled templates (#112).

**Comment by kaspermeyer** [comment]
@joelhawksley Just following up on this — I didn't get time and the end of last week as I hoped, but I haven't forgotten 😌 I'll get to it as soon as I can!

**Comment by joelhawksley** [comment]
@kaspermeyer I landed a patch to Rails that adds support for component rendering: https://github.com/rails/rails/pull/37919. I might take a crack at implementing the equivalent change with a monkey patch in this gem 😄

**Comment by kaspermeyer** [comment]
@joelhawksley That's wonderful news! 👏 It's great to see more of these component related features getting upstreamed in Rails. Go nuts with the monkey patch and let me know if you need me ✌️

**Comment by sjayanna** [comment]
@joelhawksley @ushis  how would one test if the component is rendered in the controller tests using the above hack?

**Comment by mjacobus** [comment]
> P.S. Found a workaround. Maybe its a good starting point:

That workaround caused some issues with turbo - can't remember the specifics. This fixed it:

```ruby
class ApplicationController
  def render_component(component, **options)
    @component_to_render = component
    render "/view_component", **options
  end
end
```

```erb
<!-- app/views/view_component.html.erb -->
<%= render @component_to_render %>
```

**Comment by trappar** [comment]
I might have found the bugs you were talking about @mjacobus. Opened an issue here: https://github.com/ViewComponent/view_component/issues/1534
