### ISSUE TITLE
ActionView::Component previews

### ISSUE THREAD

**Issue by mikker** [github/actionview-component#40]
It struck me; AV::Components ought to have previews the same way ActionMailer does.

I realise this might be overkill for a 1.0 release but I'll be happy to throw a first draft together if you folks think it's as good an idea as I do.

Otherwise I might just make it as a gem on its own.

**Comment by xdmx** [comment]
It'd be awesome to have some kind of preview of components, with the ability of grouping the by categories/subcategories. I'm thinking about something like storybook, where you can easily navigate and search the available components.

It'd also be great having a configuration to allowing the access of it from different environments (like mailer previews), that way it could be enabled on a staging environment and having designers accessing it without having to go through the whole rails/project setup.

**Comment by xdmx** [comment]
It would also play very well with the [rails conductor](https://github.com/rails/rails/pull/35489) planned for 6.1, which from my understanding is also the planned version for merging components into rails

**Comment by joelhawksley** [comment]
@mikker this sounds great! I'd happily accept a PR for this that mimics ActionMailer previews as much as possible 😍

**Comment by tijmenb** [comment]
Hi! I'd be very interested in this. [GOV.UK](https://www.gov.uk/) has been working with components for the last couple of years, and one of the key features is the ability to spin up a "component guide" that documents all the components.

The main one is publicly available at: https://components.publishing.service.gov.uk (repo is https://github.com/alphagov/govuk_publishing_components).

For example, this is the [page title component](https://components.publishing.service.gov.uk/component-guide/title):

![Screenshot_2019-10-11 Page title component - Component Guide](https://user-images.githubusercontent.com/233676/66683668-f0fabd00-ec6f-11e9-8d06-73e3fff7261a.png)

A component guide page has:

- A description of how it should be used
- A preview
- A number of usage examples (this is super useful make sure components work visually with all inputs) plus previews
- Code snippet to use it in your template

@mikker have you started on this? I'd be up for spiking something.

**Comment by mikker** [comment]
I haven't yet so feel very free to take over 👍

I love the gov.uk guides and of course you already have something like this going.

**Comment by juanmanuelramallo** [comment]
I'd like to take this one

**Comment by juanmanuelramallo** [comment]
@mikker this issue has been addressed in #96 so I'm closing it

It's just a start btw, we can come back later and make improvements

**Comment by mikker** [comment]
Wow! That's great work! Thanks @juanmanuelramallo 💙💚💛💜❤️
