### ISSUE TITLE
ArgumentError - Missing host to link to on *_url helpers

### ISSUE THREAD

**Issue by dark-panda** [github/actionview-component#41]
The following exception occurs when trying to use a `*_url`-style route helper:

`ArgumentError - Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true:`

This occurs when the `Rails.application.routes.url_helpers` has been included in a component and you try to use any sort of `*_url` method, like `root_url` or similar.

**Comment by joelhawksley** [comment]
@dark-panda thank you for the bug report!

This is definitely something that should [_just work_](https://github.com/github/actionview-component#design-philosophy).

How do you think we should implement it?

**Comment by joelhawksley** [comment]
I believe this should be addressed in https://github.com/github/actionview-component/releases/tag/v1.3.0. Please re-open this if it isn't ❤️
