### ISSUE TITLE
Unable to render forms/button_to from a component

### ISSUE THREAD

**Issue by jcoyne** [github/actionview-component#43]
Originally posted in #15, but also a problem for me:

> Rendering a form/button_to from a component raises an error undefined method 'protect_against_forgery?' for #<Happening::SignUpButton:0x00007f893937e7f8>

we'd also need `form_authenticity_token`

**Comment by mhw** [comment]
#28 seems to be working towards addressing this issue

**Comment by jcoyne** [comment]
@mhw I agree. I've monkeypatched my project with that code and it's working well.

**Comment by joelhawksley** [comment]
I believe this should be addressed in https://github.com/github/actionview-component/releases/tag/v1.3.0. Please re-open this if it isn't ❤️
