### ISSUE TITLE
Make the controller instance in a test case be accessible. 

### ISSUE THREAD

**Issue by jcoyne** [github/actionview-component#44]
In my component I'm using the cancancan gem. This defines a controller method `can?` in the controller context.  So my component does:

```
  delegate :can?, to: :controller
```

In my test, I'd love to mock out the `controller.can?` method, but I don't think `ActionView::Component::TestHelpers` gives a way to get the controller instance.  Is it possible to expose  that?

**Comment by mikker** [comment]
You could stub the `controller` method on the component itself instead?

**Comment by jcoyne** [comment]
@mikker I'd rather not, because then I would loose access to forms (see #43).

How would one go about stubbing the controller method when you do `render_inline`?

**Comment by joelhawksley** [comment]
I believe this should be addressed in https://github.com/github/actionview-component/releases/tag/v1.3.0. Please re-open this if it isn't ❤️
