### ISSUE TITLE
Private methods should not be accessable in templates

### ISSUE THREAD

**Issue by jcoyne** [github/actionview-component#45]
Presently they are.

**Comment by joelhawksley** [comment]
@jcoyne I'd be interested to hear your reasoning why you believe this should be the case.

The current architecture expects components to be objects that have a single public instance method, `render_in`, which is called when a component is passed to `render`, or in the case of a test, `render_inline`. `render_in` in turn renders the provided template _within_ the context of the component object instance.

Given that, I think it makes sense to keep the rest of the methods on the component private, as they aren't expected to be called outside of the component. 

For instance, I don't think we'd expect one to call `MyComponent.new(foo: :bar).title`.

**Comment by joelhawksley** [comment]
Closing this as stale. Feel free to re-open ❤️
