### ISSUE TITLE
relative i18n paths

### ISSUE THREAD

**Issue by koenhandekyn** [github/actionview-component#49]
i'm getting an error that relative I18n paths are not available (Cannot use t(".register") shortcut because path is not available). Is there a know 'workaround' ?

**Comment by joelhawksley** [comment]
@koenhandekyn thank you for the issue report. Might you be able to provide a PR with a failing test for this use case?

**Comment by koenhandekyn** [comment]
i'll revalidate the issues on a 'blank slate fresh'  rails 6 app first to see if we can reproduce them there.

**Comment by juanmanuelramallo** [comment]
Here I created an example of the failure https://github.com/joelhawksley/actionview-component-demo/pull/28/files.

Should I create a PR in this repo so that we actually see tests failing?

**Comment by joelhawksley** [comment]
This should be resolved by https://github.com/github/actionview-component/pull/74. Feel free to re-open if it wasn't.

**Comment by koenhandekyn** [comment]
i can't reopen but see #74 for a proposed fix of the current issue. putting this comment as a reference.
