### ISSUE TITLE
Problems after upgrading to version 1.3.0

### ISSUE THREAD

**Issue by afuno** [github/actionview-component#50]
I used version 1.2.1. Everything was fine. Today I upgraded to version 1.3.0. And part of my components broke.

For example, there is such a component:

```ruby
class ParagraphComponent < ActionView::Component::Base
  validates :content, presence: true

  def initialize(html: {})
    @html = html
  end

  private

  def additional_classes
    return '' if @html.empty?
    return '' if @html[:class].blank?

    @html[:class]
  end

  def classes
    [
      'm:text-18 m:leading-2',
      't:text-24 t:leading-1.5',
      'd:text-24 d:leading-1.5',
      additional_classes
    ].join(' ')
  end
end
```

And the template:

```slim
= content_tag :div, class: classes
  = content
```

Next, I use this component, for example, this way:

```slim
= render(ParagraphComponent, html: { class: 'flex flex-row mb-6' })
  = content_tag :div, class: 'mr-20'
    | First
  = content_tag :div
    | Second
```

As a result, in the code of the source page, I do not see the classes from the component. That is, I immediately see the code from the `content` variable.

In general, all the HTML code on the page (including Vue components) does not behave appropriately. HTML code breaks. Tags (elements, nodes) are simply incorrect.

The problem is precisely related to your gem. If I write the following in Gemfile:

```
gem 'actionview-component', '1.2.1'
```

Then there are no more problems. Everything works fine again.

But as soon as I upgrade to version 1.3.0, everything breaks down again.

I have never seen anything like this before.

**Comment by afuno** [comment]
I can’t understand what exactly is the problem. But this is precisely related to version 1.3.0. As I wrote above - version 1.2.1 is stable.

**Comment by joelhawksley** [comment]
@afuno thanks for the report. I'm seeing something similar on our end. 

Might you be able to provide a PR with a failing test?

**Comment by joelhawksley** [comment]
@afuno this should be fixed in v1.3.1. Can you check? Going to go ahead and close this issue, but please reopen it if this is still occurring in v1.3.1 ❤️

**Comment by afuno** [comment]
@joelhawksley Thank you for your prompt work. I will check the new version in the coming hours time and write to you.

**Comment by afuno** [comment]
@joelhawksley Everything is fine. Thanks.
