### ISSUE TITLE
simple path helpers not working, need explicit id passing

### ISSUE THREAD

**Issue by koenhandekyn** [github/actionview-component#51]
we are implementing the current release into our project, which we recently have brought to rails 6. path helpers require for some reason that you explicitly pass the id, so we need to change edit_instrument_path(instrument) into edit_instrument_path(id: instrument.id).

this feels like unintended / a bug. any fixes?

**Comment by joelhawksley** [comment]
@koenhandekyn I agree that this should work. I will happily accept a PR ❤️ 😄

**Comment by joelhawksley** [comment]
@koenhandekyn I attempted to reproduce this issue in a test on the gem, and I couldn't seem to get a failure. If you could provide a demo Rails app, or a PR to this repo with a failing test, that would be super helpful!

**Comment by koenhandekyn** [comment]
i'll revalidate the issues on a 'blank slate fresh' rails 6 app first to see if we can reproduce them there.

**Comment by koenhandekyn** [comment]
the issue seems to be related to the combination of using a namespace (scope) in the routes table (e.g. `scope "/c/(:c)" do`) in combination with default_url_options in our application controller that refers to current_user. the question whether or not this is to be seen as a bug (or not) is probably more a question for the path helpers codebase and not so much for the actionview components code, though a question for the actionview components team might be whether it would not be more intuitive to the users to make sure helpers like current_user are actually available.

currently we are passing around current_user explicitly, which i don't fundamentally object to, though there are some places where you simply can't pass on current_user (like when user in the context of path helpers).

we'll probably be able to work around this. the reasons why we where using the current_user in the path helper context was for purpose of cache busting, but we might be able to do that differently. 

```
  def default_url_options
    {c: current_user&.customer_id || params[:c].to_i}
  end
```

**Comment by koenhandekyn** [comment]
mm, i just saw #59. it seems you already have decided that access to the request scope makes sense :)

**Comment by joelhawksley** [comment]
@koenhandekyn thanks for following up. Might you be able to see if `1.3.4`'s including of the `request` context addresses this? Feel free to re-open if it doesn't ❤️
