### ISSUE TITLE
Best practice for CSS?

### ISSUE THREAD

**Issue by AlecRust** [github/actionview-component#55]
I have a component structure like so:

```
- /app
  - /components
    - /alert
      - alert.css
      - alert.html.erb
      - alert.rb
```

I'm importing the CSS file in Webpacker's `application.css`.

Unfortunately this setup gives me the error:

```
More than one template found for Alert. There can only be one sidecar template file per component.
```

I'm currently working around this by using `_alert.css` instead of `alert.css`, but it seems odd `actionview-component` is treating this CSS file as a template file?

Is there a best practice here I should be following? Or is this an issue `actionview-component` should fix?

**Comment by joelhawksley** [comment]
@AlecRust you're right, `actionview-component` should only raise an error if there is more than one template file. It shouldn't care if there is a sidecar CSS file.

**Comment by joelhawksley** [comment]
@AlecRust can you check your app against v1.3.3 to see if this is fixed for you?

**Comment by AlecRust** [comment]
@joelhawksley works great, many thanks!
