### ISSUE TITLE
1.3.3 release broken?

### ISSUE THREAD

**Issue by koenhandekyn** [github/actionview-component#63]
we had to step down to 1.3.1 release because our templates are not found on 1.3.3. our developer traced this to the following

in version 1.3.1. we have this:

sibling_files = Dir["#{filename_without_extension}.*"] - [filename]
It will find the files in the path: XYZ/app/components/page/paginate.*

THIS IS WORKING, we have a file pagina.slim in the folder

but in 1.3.3 we have this

sibling_template_files = Dir["#{filename_without_extension}.????.{#{ActionView::Template.template_handler_extensions.join(',')}}"] - [filename]

it will find the files in the path: XYZ/app/components/page/paginate.????{arb,builder,coffee,erb,html,jbuilder,raw,ruby,slim}

THIS IS NOT WORKING, it does not find the file paginate.slim anymore

**we are following the naming convention to not have .html.slim similar to the normal recommendations in rails and have .slim** (and this was working)

related to these commits

https://github.com/github/actionview-component/commit/fbbeab1a754e80c4cb0f7aa675f0ee54bba4ac9c#diff-4ea3d395eff742fa0d8952d23a16d377

https://github.com/github/actionview-component/commit/fbbeab1a754e80c4cb0f7aa675f0ee54bba4ac9c#diff-4ea3d395eff742fa0d8952d23a16d377

**Comment by joelhawksley** [comment]
@koenhandekyn thank you for the report. Sorry if this caused you any pain ❤️ 

_At least from what I've read_, Rails templates are _supposed_ to be in the format `name`.`format`.`handler`. However, Rails does support omitting the `format`, likely for backwards compatibility.

For now, the fix would be to rename the templates to include the format. That being said, we probably should allow folks to omit the format.

**Comment by koenhandekyn** [comment]
we'll survive ;) 

thoughts: 

- as a minor version update, it is surely an unexpected change :)
- if this is going to become rails core, it will probably make sense to align this with the rest of rails, either require it everywhere or else allow to omit everywhere :) 
- personally i could accept a general rails policy that a format is 'mandatory' everywhere :)

**Comment by joelhawksley** [comment]
Closing in favor of https://github.com/github/actionview-component/issues/78.
