### ISSUE TITLE
image_url and image_tag ignoring configured asset_host value

### ISSUE THREAD

**Issue by mellowfish** [github/actionview-component#69]
When I call `image_url("some_image.png")` directly in my views, I am getting a relative path vs a full asset url (which in our case is a CDN).

If I call `view_context.image_url("some_image.png")` it works fine and generates the full url.

Similar issues for `image_tag` which delegates to the same method.

I have temporarily added a `delegate :image_url, :image_tag, to: :view_context` in my component, but this feels wrong.

Is there something I am missing about how to configure this, or is this an actual bug?

**Comment by cjbottaro** [comment]
I'm seeing the same thing. Tracked it down to `config.asset_host` returning nil.

So it seems that `@_config` needs to be set to `view_context.config` or something like that.

**Comment by mellowfish** [comment]
Curious, I see a `include ActiveSupport::Configurable`, but no actual references to `config` or `configure`. Can we just delegate the `config` method to `view_context`, or were components meant to be separately configurable?

**Comment by joelhawksley** [comment]
@mellowfish might you be able to test this issue against `v1.3.5`?

**Comment by mellowfish** [comment]
@joelhawksley was away on vacation. It looks like v1.3.5 still doesn't properly insert the asset_host config value.

**Comment by mellowfish** [comment]
Looks like `helpers.image_url` and the like should work.
