### ISSUE TITLE
How to access controller helper methods?

### ISSUE THREAD

**Issue by juanmanuelramallo** [github/actionview-component#70]
## Question
Is there a way to access controller helper methods? (The ones created like this https://api.rubyonrails.org/classes/AbstractController/Helpers/ClassMethods.html#method-i-helper_method)

## Why
We may want to use controller helper methods like [Devise](https://github.com/plataformatec/devise)'s ones (`current_user`, `user_signed_in?`), or any other helper method defined by the application.

**Comment by juanmanuelramallo** [comment]
I think I just answered to my own question. 

We would just need to pass them as arguments in the render call, right? 

So we keep components clean and less prone to nil errors due to these external attributes.

**Comment by crolla97** [comment]
Hey @juanmanuelramallo do you have any examples of how you called and used the `user_signed_in?` helper method? Pretty new to rails still and struggling to find the solution thanks!

**Comment by AlecRust** [comment]
I too am looking for a good solution to this.

**Comment by damel** [comment]
add `include Devise::Controllers::Helpers ` to component.
`def render 
user_signed_in? 
end`

**Comment by juanmanuelramallo** [comment]
Have you tried the `helpers` proxy method? https://github.com/github/view_component#using-helpers

When I opened this issue the `helpers` method wasn't developed yet. So I just passed the values when instantiating the components in the views.

```html+erb
# app/views/some_resource/some_template.html.erb

<%= render MyComponent.new(user_signed_in: user_signed_in?) %>
```

But I think now you can use the `helpers` proxy.

**Comment by sunny** [comment]
Yes, using the `helpers` proxy works well! As for tests, I had to use the following configuration to test my components with Devise’s middleware.

```rb
RSpec.configure do |config|
  config.include Devise::Test::ControllerHelpers, type: :component

  config.before(:each, type: :component) do
    @request = controller.request
  end
end
```

**Comment by DiegoOrejuela** [comment]
> ```ruby
> config.include Devise::Test::ControllerHelpers, type: :component
> ```

This should be in docs! 🎉

**Comment by DiegoOrejuela** [comment]
> Yes, using the `helpers` proxy works well!
> 
> As for tests, I had to use the following configuration to test my components that used methods such as `helpers.current_user`.
> 
> ```ruby
> RSpec.configure do |config|
>   config.include Devise::Test::ControllerHelpers, type: :component
> 
>   config.before(:each, type: :component) do
>     @request = controller.request
>   end
> end
> ```

This should be in docs! 🎉

**Comment by patchwork-her** [comment]
I mean if it's that simple it should be something! Documented I am sure
just like you just did.

**Comment by joelhawksley** [comment]
> This should be in docs! 🎉

I agree. Mind writing a PR @DiegoOrejuela?

**Comment by DiegoOrejuela** [comment]
Oh, yes. Thanks.
