### ISSUE TITLE
1.3.5 release resolves paths wrongly?

### ISSUE THREAD

**Issue by koenhandekyn** [github/actionview-component#78]
sorry ... duplicate from previous ticket ... seems the framework still is expecting .html.slim extension and not .slim extension (which is painful because in other places we actually have issues with .html.slim as extension where we need to make it .slim)

**Comment by joelhawksley** [comment]
@koenhandekyn `1.3.5` did not contain any changes meant to fix this issue. We'd happy accept a PR!
