### ISSUE TITLE
not an ActiveModel-compatible object. It must implement :to_partial_path.

### ISSUE THREAD

**Issue by benreyn** [github/actionview-component#79]
Freshly installed `actionview-component` (version `1.3.5`) on rails version `6.0` with the following setup...

`config/application.rb`
```ruby
# snip...
require "action_view/component/base"
# snip...
```

`app/components/application_component.rb`
```ruby
class ApplicationComponent < ActionView::Component::Base
end
```

`app/components/example_component/example_component.rb`
```
class ExampleComponent < ApplicationComponent
  validates :content, presence: true

  def initialize(message:)
    @message = message
  end

  attr_reader :message
end
```

`app/components/example_component/example_component.slim`
```slim
div
  = content
  = message
```

and in a view file...
```slim
body
  h2
    | Example Component:
  = render(ExampleComponent, message: "Hello, World!") do
    | This is an example component...
```

Results in....
```
'ExampleComponent' is not an ActiveModel-compatible object. It must implement :to_partial_path.
```

Any tips on what I might be missing here?

**Comment by benreyn** [comment]
Poking around with this a bit more and it looks like the line... 
`require "action_view/component/base"`
is silently failing and returning `false` but interestingly
`require "action_view/component/test_helpers"` succeeds

**Comment by DylanReile** [comment]
In our case the nesting of `app/components/example_component/example_component.rb` caused Rails to autovivify the `ExampleComponent` module. Action component was looking for `:to_partial_path` on the module instead of the class.

We fixed it by removing the nesting.

**Comment by joelhawksley** [comment]
I believe @DylanReile is correct here. Feel free to reopen if desired ❤️

**Comment by dark-panda** [comment]
Sorry to raise this issue from the grave, but I've installed this gem on a Rails 5.2.3 project and it gives this same error as of version 1.5.1. Version 1.3.5 worked. Any hints?

**Comment by ozzyaaron** [comment]
We got this error on a Rails 6.0.0 app by upgrading to from actionview-component 1.4.0 to 1.5.2. 

Investigating now ...

**Comment by ToTenMilan** [comment]
In my case, I needed to do
```ruby
gem "view_component", '~> 2.22', '>= 2.22.1', require: "view_component/engine"
```
as Github docs suggest, instead of
```
gem 'view_component'#, '~> 2.22', '>= 2.22.1'`
```
as ruby gems snippet suggests
