### ISSUE TITLE
Remove initializer requirement for Ruby 2.7

### ISSUE THREAD

**Issue by joelhawksley** [github/actionview-component#93]
Per https://blog.saeloun.com/2019/09/17/ruby-2-7-module-const-source-location.html, we should be able to remove the requirement of having initializers in Ruby 2.7.

**Comment by dylnclrk** [comment]
I took a stab at this here: dylnclrk#1, but it seems like we're a bit blocked because doesn't yet support Ruby 2.7 (actions/setup-ruby#45).

**Comment by bostanio** [comment]
@dylnclrk Can you make that a PR on against this repo so we can have the conversation here?

**Comment by dylnclrk** [comment]
@bostanio done (#174). Was thinking I didn't want to clutter up the PRs here with stuff that wasn't totally ready, but you're right, it will get confusing.

**Comment by dylnclrk** [comment]
PR #174 (merged) closes this, right? Should we wait for a release to close the issue?

**Comment by joelhawksley** [comment]
Closing this for now as we've had issues with this approach and Zeitwerk.
