### ISSUE TITLE
Support `helpers.` syntax

### ISSUE THREAD

**Issue by joelhawksley** [github/actionview-component#95]
It would be wonderful if we could support the `helpers` syntax in components, much like @rafaelfranca added for controllers in https://github.com/rails/rails/pull/24866.

**Comment by kaspermeyer** [comment]
I can take a stab at this, @joelhawksley ✌️

**Comment by joelhawksley** [comment]
@kaspermeyer 😍 thanks! I've assigned this to you so no one else takes it 😄
