### ISSUE TITLE
Add component generator

### ISSUE THREAD

**Issue by joelhawksley** [github/actionview-component#97]
@vinistock I heard you might have made some progress on this. Would you be interested in sharing what you have so far?

**Comment by vinistock** [comment]
Absolutely. I played around a bit using a generator to create a component class with its respective html template and test.

I also experimented a bit around having the generator create javascript files for each component (which could be too much, but I was exploring different ideas).

The general goal would be to have something like this:
```bash
bin/rails g component MyComponent name age
```

That would create the files for a component with two attributes (name and age).

I can put together a pull request and we can iterate on getting the generator right. What do you think?

**Comment by joelhawksley** [comment]
@vinistock a PR sounds great! 

I think we should wait on the JS bit, as I'm wary of implying that components encapsulate JS, when they currently do not.
